name: getLints

on:
  schedule:
  - cron: "0 0 * * *"  # Run every day
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  getLints:
    environment: production
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Save all.yaml file
        shell: pwsh
        run: curl "https://raw.githubusercontent.com/dart-lang/linter/master/example/all.yaml" -o lib/all.yaml
      
      - name: Commit if file changed
        uses: stefanzweifel/git-auto-commit-action@v4.14.0
        with:
            commit_message: Copy all.yaml
  publish:
      container:
       image:  google/dart:latest
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
               # if: steps.auto-commit-action.outputs.changes_detected == 'false'
        - name: Install dependencies
          run: pub get
        - name: Setup Pub Credentials
          shell: bash
          env:
            PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
            PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
            PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
            PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
          run: |
            sh ./pub_login.sh
        - name: Check Publish Warnings
          run: pub publish --dry-run
        - name: Publish Package
          run: pub publish -f

